#!/usr/bin/env zsh
# William G. Scott/Wataru Kagawa 

if [[ -d $ZDOTDIR/gdirs/functions ]];then
 fpath=($ZDOTDIR/gdirs/functions $fpath)
fi

# ---[ Alias Section ]-------------------------------------------------
alias dirstack="dirdump; typeset -U dirs_shared ; dirstack"
alias cd\?="dirdump; typeset -U dirs_shared; dirstack"
alias gdirs="dirdump; typeset -U dirs_shared; dirstack > /dev/null ; _guidirs"
# dvorak case
alias cdL="dirdump; typeset -U dirs_shared; dirstack" # as L is near ?
alias cdl="dirdump; typeset -U dirs_shared; dirstack" # easier to type than cd?

##if [[ -f $ZDOTDIR/cache/dirstack ]] && [[ ${#dirstack[*]} -eq 0 ]]; then
## dirstack=( ${(uf)"$(< $ZDOTDIR/cache/dirstack)"} )
## echo "Loaded the dirstack from disk..."
##fi
##chpwd() { dirs -pl >! $ZDOTDIR/cache/dirstack }

